name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  precheck:
    name: Check things
    uses: ./.github/workflows/check.yml
    secrets: inherit

  prepare_db:
    name: Prepare database
    uses: ./.github/workflows/prepare_db.yml
    secrets: inherit
    needs: precheck
    with:
      d1_database_name: ${{ needs.precheck.outputs.d1_database_name }}
      d1_database_id: ${{ needs.precheck.outputs.d1_database_id }}
      create_database: ${{ needs.precheck.outputs.d1_apparent_database_id == 'null' }}

  deploy_pages:
    name: Deploy CloudFlare Pages
    uses: ./.github/workflows/deploy_pages.yml
    secrets: inherit
    needs: precheck
    with:
      pages_name: ${{ needs.precheck.outputs.worker_name }}
      worker_url: ${{ needs.precheck.outputs.worker_url }}
  
  deploy_worker:
    name: Deploy CloudFlare Worker
    uses: ./.github/workflows/deploy_worker.yml
    secrets: inherit
    needs: [precheck, prepare_db, deploy_pages]
    with:
      d1_database_id: ${{ needs.precheck.outputs.d1_database_id }}
      d1_apparent_database_id: ${{ needs.prepare_db.outputs.d1_apparent_database_id }}
      pages_url: ${{ needs.deploy_pages.outputs.pages_url }}
      worker_url: ${{ needs.precheck.outputs.worker_url }}
  
  finalise:
    name: Final output
    uses: ./.github/workflows/finalise.yml
    secrets: inherit
    needs: [deploy_worker, deploy_pages, prepare_db]
